version: '3.9'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
      POSTGRES_DB:       "ostock_dev"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: config-server:latest
    ports:
       - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"
  eurekaserver:
    image: eureka-server:latest
    depends_on:
      configserver:
          condition: service_started
    ports:
      - "8070:8070"
    networks:
      backend:
        aliases:
          - "eureka-server"
  licensingservice:
    image: licensing-service:latest
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    environment:
      - "spring.profiles.active=dev"
    ports:
      - "8080:8080"
    networks:
      - backend
  organizationservice:
    image: organization-service:latest
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge