eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,env,refresh,beans
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    refresh:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true